const actions = {
  food: {
    DATA_FETCHING: "MENU_DATA_FETCHING",
    DATA_FETCHED: "MENU_DATA_FETCHED",
    DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
    FILTER_BY_SELECT: "FILTER_BY_SELECT",
    FILTER_BY_FIELD: "FILTER_BY_FIELD",
    FILTER_BY_RANGE: "FILTER_BY_RANGE",
  },
};
export default actions;
